config/routes.rb
Rails.application.routes.draw do
  resources :elements
  resources :posts
  devise_for :authors
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :post

  validates :element_type, inclusion: { in: ['paragraph', 'image', 'video-embed']}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :elements
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_post
  before_action :set_element, only: [:update, :destroy]


  # POST /elements
  def create
    @element = @post.elements.build
    if @element.save
      redirect_to @post
    else
      redirect_to @post, notice: @element.errors.full_messages
    end
  end
  # .join(". ") << "."
  # PATCH/PUT /elements/1
  def update
    if @element.update(element_params)
      redirect_to @element, notice: 'Element was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /elements/1
  def destroy
    @element.destroy
    redirect_to elements_url, notice: 'Element was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_post
      @post = current_author.posts.find(params[:post_id])
    end

    def set_element
      @element = @post.elements.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def element_params
      params.require(:element).permit(:element_type, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :authenticate_author!
  # GET /posts
  def index
    @posts = current_author.posts
  end


  # GET /posts/new
  def new
    @post = current_author.posts.build
  end

  # GET /posts/1/edit
  def edit
    @paragraph = @post.elements.build(element_type: 'paragraph')
  end

  # POST /posts
  def create
    @post = current_author.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_author.posts.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/elements/_form.html.erb
<%= form_with(model: element, local: true) do |form| %>
  <% if element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
        <% element.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :element_type %>
    <%= form.text_field :element_type %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/elements/edit.html.erb
<h1>Editing Element</h1>

<%= render 'form', element: @element %>

<%= link_to 'Show', @element %> |
<%= link_to 'Back', elements_path %>

app/views/elements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Elements</h1>

<table>
  <thead>
    <tr>
      <th>Element type</th>
      <th>Content</th>
      <th>Post</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elements.each do |element| %>
      <tr>
        <td><%= element.element_type %></td>
        <td><%= element.content %></td>
        <td><%= element.post_id %></td>
        <td><%= element.position %></td>
        <td><%= link_to 'Show', element %></td>
        <td><%= link_to 'Edit', edit_element_path(element) %></td>
        <td><%= link_to 'Destroy', element, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Element', new_element_path %>

app/views/elements/new.html.erb
<h1>New Element</h1>

<%= render 'form', element: @element %>

<%= link_to 'Back', elements_path %>

app/views/elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Element type:</strong>
  <%= @element.element_type %>
</p>

<p>
  <strong>Content:</strong>
  <%= @element.content %>
</p>

<p>
  <strong>Post:</strong>
  <%= @element.post_id %>
</p>

<p>
  <strong>Position:</strong>
  <%= @element.position %>
</p>

<%= link_to 'Edit', edit_element_path(@element) %> |
<%= link_to 'Back', elements_path %>

app/views/home/index.html.erb
<% if author_signed_in? %>
  <h1>Welcome, <%= current_author.email %></h1>
<% else %>
  <h1>Welcome New Guy</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-4">
    <%= form.label :title, class: 'mb-2' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field mb-4">
    <%= form.label :description, class: 'mb-2' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn-primary col-12' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class='container'>
  <%= link_to 'Back', posts_path, class: 'btn btn-secondary mb-3 mt-3' %>
  <div class="row">
    <div class="col-md-3">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Editing Post</h4>
          <%= render 'form', post: @post %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <%= form_with(model: [@posts_path, @paragraph]) do |form| %>
      <%= form.submit %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class = 'container'>
  <h3 class = 'd-flex justify-content-between mb-4 mt-4'>
    <span>Post</span>
    <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
  </h3>
  <% @posts.each do |post|%>
    <%= link_to edit_post_path(post), class: 'text-decoration-none' do %>
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title mb-1 text-dark"><%= post.title%></h5>
          <p class="text-secondary mb-0"><%= post.description %></p>
        </div>
      </div>
    <% end %>
  <% end%>
  
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">BLOG</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if author_signed_in? %>
          <li class="nav-item">
           <%= link_to 'New Post',   new_post_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign out',  destroy_author_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
           <%= link_to 'Register',  new_author_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign in',  new_author_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>